import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-background': 'var(--color-primary-background)',
        'primary-text': 'var(--color-primary-text)',
        'primary-white': 'var(--color-primary-white)',
        'primary-black': 'var(--color-primary-black)',
        'semantic-blue': 'var(--color-semantic-blue)',
        'semantic-red': 'var(--color-semantic-red)',
        'semantic-green': 'var(--color-semantic-green)',
        'semantic-orange': 'var(--color-semantic-orange)',
        'semantic-yellow': 'var(--color-semantic-yellow)',
        'semantic-indigo': 'var(--color-semantic-indigo)',
        'scrollbar': 'var(--color-scrollbar)',
        'scrollbar-hover': 'var(--color-scrollbar-hover)',
        'scrollbar-active': 'var(--color-scrollbar-active)',
        'focus-ring': 'var(--color-focus-ring)',
      },
      fontFamily: {
        regular: 'var(--font-family-regular)',
        serif: 'var(--font-family-serif)',
        mono: 'var(--font-family-mono)',
        emoji: 'var(--font-family-emoji)',
      },
      fontSize: {
        tiny: 'var(--font-size-tiny)',
        micro: 'var(--font-size-micro)',
        mini: 'var(--font-size-mini)',
        small: 'var(--font-size-small)',
        regular: 'var(--font-size-regular)',
        large: 'var(--font-size-large)',
        title1: 'var(--font-size-title1)',
        title2: 'var(--font-size-title2)',
        title3: 'var(--font-size-title3)',
        title4: 'var(--font-size-title4)',
        title5: 'var(--font-size-title5)',
        title6: 'var(--font-size-title6)',
        title7: 'var(--font-size-title7)',
        title8: 'var(--font-size-title8)',
        title9: 'var(--font-size-title9)',
      },
      fontWeight: {
        light: 'var(--font-weight-light)',
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },
      lineHeight: {
        tight: 'var(--line-height-tight)',
        normal: 'var(--line-height-normal)',
        relaxed: 'var(--line-height-relaxed)',
        loose: 'var(--line-height-loose)',
        'extra-loose': 'var(--line-height-extra-loose)',
      },
      letterSpacing: {
        tight: 'var(--letter-spacing-tight)',
        normal: 'var(--letter-spacing-normal)',
        relaxed: 'var(--letter-spacing-relaxed)',
      },
      borderRadius: {
        small: 'var(--radius-small)',
        medium: 'var(--radius-medium)',
        large: 'var(--radius-large)',
        xl: 'var(--radius-xl)',
        xxl: 'var(--radius-xxl)',
        xxxl: 'var(--radius-xxxl)',
        huge: 'var(--radius-huge)',
        full: 'var(--radius-full)',
        circle: 'var(--radius-circle)',
      },
      spacing: {
        'page-padding-inline': 'var(--spacing-page-padding-inline)',
        'page-padding-block': 'var(--spacing-page-padding-block)',
        'min-tap-size': 'var(--spacing-min-tap-size)',
      },
      maxWidth: {
        'page-max': 'var(--layout-page-max-width)',
        'prose-max': 'var(--layout-prose-max-width)',
      },
      zIndex: {
        max: 'var(--layer-max)',
        debug: 'var(--layer-debug)',
        'skip-nav': 'var(--layer-skip-nav)',
        'context-menu': 'var(--layer-context-menu)',
        tooltip: 'var(--layer-tooltip)',
        toasts: 'var(--layer-toasts)',
        dialog: 'var(--layer-dialog)',
        'dialog-overlay': 'var(--layer-dialog-overlay)',
        'command-menu': 'var(--layer-command-menu)',
        popover: 'var(--layer-popover)',
        overlay: 'var(--layer-overlay)',
        header: 'var(--layer-header)',
        scrollbar: 'var(--layer-scrollbar)',
        footer: 'var(--layer-footer)',
      },
    },
  },
  plugins: [],
};

export default config;

